markdown: kramdown
title: FlarumOne â€“ Forums Made Simple
email: support@flarumone.com
description: "Flarum is the next-generation forum software that makes online discussion fun. It's simple, fast, and free."
baseurl: ""
url: "http://home.flarumone.com"
google_analytics_id: UA-44566935-2
kramdown:
  input: GFM

collections:
  docs:
    output: true
